api/urls.py
from django.urls import path, re_path
from . import views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # re_path(r'^(?P<version>(v1))/mapillary/token/verify', views.MapillaryTokenVerify.as_view(), name='api.mapillary.token_verify'),
    re_path(r'^(?P<version>(v1))/sequence/create', views.SequenceCreate.as_view(), name="api.sequence.create"),
    re_path(r'^(?P<version>(v1))/sequence/import/(?P<unique_id>[\w-]+)/$', views.SequenceImport.as_view(), name="api.sequence.import"),
    # re_path(r'^(?P<version>(v1|v2))/sequence/import', views.SequenceImport.as_view(), name="api.sequence.import"),
]

accounts/forms.py
## Django Packages
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django import forms
from django.utils.text import capfirst
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.utils.translation import gettext, gettext_lazy as _

## App Packages
from .models import CustomUser

UserModel = get_user_model()

############################################################################

class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """
    email = forms.CharField(
        label=_("Email"),
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '', 'autofocus': True})
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password'}),
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(email)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        # Set the max length and label for the "username" field.
        self.email_field = UserModel._meta.get_field(UserModel.EMAIL_FIELD)
        if self.fields['email'].label is None:
            self.fields['email'].label = capfirst(self.email_field.verbose_name)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:

                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return forms.ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'email': self.email_field.verbose_name},
        )

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

class UserSignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserSignUpForm, self).__init__(*args, **kwargs)

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': ''})
    )

    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': ''})
    )

    is_maillist = forms.BooleanField(widget=forms.CheckboxInput(attrs={'checked': 'checked'}),label='Email me about imagery capture competitions', required=False)

    class Meta:
        model = CustomUser
        fields = ("email", "username", "password1", "password2", "is_maillist")

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '', 'readonly': 'true'}))

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'data-validation': 'required'}),
        required=False
    )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'data-validation': 'required'}),
        required=False
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'data-validation': 'required'}),
        required=False
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'rows': 4, 'style': 'resize: none;'}),
        required=False
    )

    website_url = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'style': 'resize: none;', 'data-validation': 'url'}), required=False)

    class Meta:
        model = CustomUser
        fields = ("username", "email", "first_name", "last_name", "description", "website_url")

class UserProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control disabled', 'readonly': 'readonly'}), required=False)

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))

    is_maillist = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'd-none', 'checked': 'checked'}),label='Email me about imagery capture competitions', required=False)

    class Meta:
        model = CustomUser
        fields = ("username", "email", "is_maillist")

class UserPasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'current-password', 'autofocus': True}),
    )

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
    )

class UserAvatarForm(forms.ModelForm):
    avatar = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = CustomUser

        fields = (
            'avatar',
        )

templates/app_download.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
{% block app_uploader %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/uploader_style.css' %}">{% endblock %}
<div class="main-body">
    <div class="container">
        <div class="row mt-3">
            <div class="text-center col-md-6">
                <a  href="https://test.com">
                    <img src="https://user-images.githubusercontent.com/1296409/91702290-6c0edf80-eb70-11ea-9c13-48b3ed7cc0a0.jpg" />
                </a>
            </div>

            <div class="text-center col-md-6">
                <a href="https://test.com">
                    <img src="https://user-images.githubusercontent.com/1296409/91702292-6c0edf80-eb70-11ea-8155-15850525dace.png" />
                </a>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal fade" id="uploadPictureModal" tabindex="-1" role="dialog" aria-labelledby="uploadPictureModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="uploadPictureModalLabel">Upload Picture</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="file-upload">
                    <form action="{% url 'account.ajax_upload_file' %}" class="dropzone ml-auto mr-auto d-flex align-items-center justify-content-center">
                      <div class="fallback">
                        <input name="avatar" type="file" multiple="false" />
                      </div>
                    </form>
                    <div class="text-right mt-3">

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary d-none" id='uploadfile'>Upload</button>
                <button type="button" class="btn btn-danger d-none" id="removefile">Remove</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="userDetailModal" tabindex="-1" role="dialog" aria-labelledby="userDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                    <h5 class="modal-title" id="userDetailModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="main-user-form">
                    <form method="POST" class="post-form" id="user_edit_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary save-btn" id="user_save_button">Save changes</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
    $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
    });

    $('#user_cancel_button').click(function () {
        $('.main-user-form').addClass('d-none');
        $('.main-user').removeClass('d-none');
    });
    $('#user_save_button').click(function () {
        if ($('#user_edit_form').isValid()) {
            $.ajax({
                url: "{% url 'account.ajax_user_update' %}",
                type: 'POST',
                data: $('#user_edit_form').serialize(),
                dataType: 'json',
                success: function (data) {
                    if (data.status == 'failed')
                        toastr.error(data.message);
                    else
                    {
                        toastr.success(data.message);
                        var user = data.user;
                        $('.main-user .user-email h5').html(user.email);
                        $('.main-user .user-name p').html(user.first_name + ' ' + user.last_name);
                        $('.main-user .user-description p').html(user.description);
                        $('.main-user .user-website').html('<a class="" href="' + user.website_url + '">' + user.website_url + '</a>');
                    }
                    $('#userDetailModal').modal('hide');
                }
            });
        }
    });

    Dropzone.autoDiscover = false;
    {% if current_user.avatar == '' or current_user.avatar is None %}
        var server_image = false;
    {% else %}
        var server_image = true;
    {% endif %}

    var myDropzone = new Dropzone(".dropzone", {
        autoProcessQueue: false,
        uploadMultiple: false,
        parallelUploads: 1,
        paramName: "avatar", // The name that will be used to transfer the file
        maxFilesize: 20,
        {#addRemoveLinks: true,#}
        maxFiles: 1,
        thumbnailWidth: 200,
        thumbnailHeight: 200,
        sending: function(file, xhr, formData) {
            formData.append("csrfmiddlewaretoken", '{{ csrf_token }}');
        },
        init: function() {
            this.on("maxfilesexceeded", function(file) {
                this.removeAllFiles();
                this.addFile(file);
            });
            this.on("success", function(file, responseText) {
                toastr.success('A picture is updated successfully.');
            });
            this.on("thumbnail", function(file, dataUrl) {
                $('.dz-image').css('border-radius', '0px');
                $('.dz-image img').css('width', '100%');
                $('.dz-image img').css('height', '100%');
                $('.dz-details').remove();
                $('.dropzone .dz-preview').off('hover');
            });
            this.on('addedfile', function () {
                $('#uploadfile').removeClass('d-none');
                $('#removefile').removeClass('d-none');
                if (server_image)
                    $('#cancelfile').removeClass('d-none');
                else
                    $('#cancelfile').addClass('d-none');
            });
            this.on('removedfile', function () {
                $('#uploadfile').addClass('d-none');
                $('#removefile').addClass('d-none');
            });
            this.on('complete', function () {
                var h = $('.dz-image').html();
                $('.dz-image-cover').html(h);
                server_image = true;
                this.removeAllFiles();
                $('#cancelfile').addClass('d-none');
                $('#uploadPictureModal').modal('hide');
                $('#user_cover_image').removeClass('d-none');
            });

            $('#change_file').click(function () {
                $('#user_cover_image').addClass('d-none');
                $('#file-upload').removeClass('d-none');
            });
        }
    });

    $('#cancelfile').click(function () {
        myDropzone.removeAllFiles();
        $('#user_cover_image').removeClass('d-none');
        $('#file-upload').addClass('d-none');
    });

    $('#removefile').click(function () {
        myDropzone.removeAllFiles();
    });

    $('#uploadfile').click(function(){
        myDropzone.processQueue();
    });
</script>

<script>
    function switch_maillist() {
        if ($('#id_is_maillist').hasClass('d-none'))
        {
            $('#id_is_maillist').prev().addClass('d-none');
        }
        else {
            $('#id_is_maillist').prev().addClass('d-none');
        }
    }

    switch_maillist()
</script>
{% endblock %}

templates/home.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_home %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/home_style.css' %}">{% endblock %}
{% block content %}

<div class="main-body">
    <div class="left-side d-flex flex-column justify-content-between">
        <div>
            <div class="p-3">
                <div class="pt-3 mb-3">
                    <h3>
                        Map the Paths
                    </h3>
                </div>
                <div class="challenge-body">
                    <p>
                        {{ pageDescription }}
                    </p>
                </div>
            </div>
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            {% endif %}

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'sequence.index' %}">
                        Sequences
                    </a>
                </div>
                <div class="card-body">
                    Sequences are collections of images continuously captured by a user at a give time. Browse those created by others, or import your own from Mapillary.
                </div>
            </div>

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'tour.index' %}">
                        Tours
                    </a>
                </div>
                <div class="card-body">
                    Tours are collections of sequences that have been curated by their owner. Browse others' tours or create one using your own sequences.
                </div>
            </div>

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'guidebook.home' %}">
                        Guidebooks
                    </a>
                </div>
                <div class="card-body">
                    Create a guidebook of street-level photos to show people around a location. View others people have created to help plan your next adventure.
                </div>
            </div>

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'challenge.index' %}">
                        Challenges
                    </a>
                </div>
                <div class="card-body">
                    Help make better maps by contributing to challenges with specific requests for imagery.
                </div>
            </div>

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'leaderboard.index' %}">
                        Leaderboard
                    </a>
                </div>
                <div class="card-body">
                    See who is topping the leaderboards for images and see where you place in the rankings.
                </div>
            </div>

            <div class="card mr-2 ml-2 mb-2">
                <div class="card-header">
                    <a href="{% url 'photographer.index' %}">
                        Hire
                    </a>
                </div>
                <div class="card-body">
                    Find paid help for image collection projects to create fresh street level map data in locations where it's needed for Google Street View, Mapillary, and more...
                </div>
            </div>

        </div>
        {% include 'components/copyrite.html' %}
    </div>
    <div class="right-board bg-light">
        <div id="map"></div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>

    mapboxgl.accessToken = mapboxToken;
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11', //hosted style id
        center: [-74.5, 40], // starting position
        zoom: 0 // starting zoom
    });
    map.addControl(new mapboxgl.NavigationControl(), 'bottom-right');
    map.on('load', function() {
    });

</script>
{% endblock %}

templates/signup.html
{% extends 'layouts/auth/base.html' %}

{% block title %}Sign Up{% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="content p-5">
            <div class="card login ml-auto mr-auto">
                <div class="card-header d-flex align-items-center">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'images/iconified/apple-touch-icon-57x57.png' %}">
                    </a>
                    <h2 class="ml-4">Sign up</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-flex flex-row justify-content-between align-items-center">
                            <a href="{% url 'login' %}">Login</a>
                            <button type="submit" class="btn btn-primary">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}