api/urls.py
from django.urls import path, re_path
from . import views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # re_path(r'^(?P<version>(v1))/mapillary/token/verify', views.MapillaryTokenVerify.as_view(), name='api.mapillary.token_verify'),
    re_path(r'^(?P<version>(v1))/sequence/create', views.SequenceCreate.as_view(), name="api.sequence.create"),
    re_path(r'^(?P<version>(v1))/sequence/import/(?P<unique_id>[\w-]+)/$', views.SequenceImport.as_view(), name="api.sequence.import"),
    # re_path(r'^(?P<version>(v1|v2))/sequence/import', views.SequenceImport.as_view(), name="api.sequence.import"),
]

challenge/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='challenge.index'),

    path('create', views.challenge_create, name='challenge.challenge_create'),
    path('<str:unique_id>/edit/', views.challenge_edit, name='challenge.my_challenge_edit'),
    path('my-list/', views.my_challenge_list, name='challenge.my_challenge_list'),
    path('list/', views.challenge_list, name='challenge.challenge_list'),
    path('<str:unique_id>/delete/', views.my_challenge_delete, name='challenge.my_challenge_delete'),
    path('<str:unique_id>/', views.challenge_detail, name='challenge.challenge_detail'),
    path('<str:unique_id>/leaderboard/', views.challenge_leaderboard, name='challenge.challenge_leaderboard'),
    path('ajax/get_challenge_detail/<str:unique_id>/', views.ajax_challenge_detail, name='challenge.ajax_challenge_detail'),
]

leaderboard/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='leaderboard.index'),
]

challenge/models.py
## Django Packages
from django.contrib.gis.db import models
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.db.models import Manager as GeoManager
from datetime import datetime
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from sequence.models import TransType, CameraMake

## Python Packages
import uuid
from django.urls import reverse

UserModel = get_user_model()

class Challenge(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    transport_type = models.ManyToManyField(TransType)
    camera_make = models.ManyToManyField(CameraMake)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    expected_count = models.IntegerField(null=True, blank=True)
    geometry = models.TextField(default='')
    multipolygon = models.MultiPolygonField(null=True, blank=True)
    is_published = models.BooleanField(default=True)
    zoom = models.FloatField(default=5)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    objects = GeoManager()

    def get_absolute_url(self):
        return reverse('challenge.challenge_detail', kwargs={'unique_id': str(self.unique_id)})

    def getShortDescription(self):
        description = self.description
        if len(description) > 50:
            return description[0:80] + '...'
        else:
            return description

    def getTrasTypes(self):
        transport_types = self.transport_type.all()
        t = []
        if transport_types.count() > 0:
            for transport_type in transport_types:
                t.append(transport_type.getFullName())

        return ', '.join(t)

    def getCameraMake(self):
        camera_makes = self.camera_make.all()
        t = []
        if camera_makes.count() > 0:
            for camera_make in camera_makes:
                t.append(camera_make.name)

        return ', '.join(t)

leaderboard/models.py
from django.db import models

# Create your models here.

leaderboard/forms.py
## Django Packages
from django import forms
from django_select2 import forms as s2forms

## App packages
from .models import *
from datetime import datetime
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from sequence.models import TransType, CameraMake
############################################################################
############################################################################

class LeaderboardSearchForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        now = datetime.now()
        year = now.year
        month = now.month



        self.fields['transport_type'] = forms.ModelChoiceField(
            required=False,
            widget=forms.Select(
                attrs={'class': 'form-control'}),
            queryset=TransType.objects.all(),
            empty_label='All Types'
        )

        self.fields['time_type'] = forms.CharField(
            label='',
            widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
            required=False
        )

        self.fields['filter_type'] = forms.ChoiceField(widget=forms.RadioSelect, choices=((0, 'Uploads'), (1, 'Distance'), (2, 'View Points')), initial=0)

        self.fields['camera_make'] = forms.ModelMultipleChoiceField(
            required=False,
            widget=forms.SelectMultiple(
                attrs={'class': 'form-control'}
            ),
            queryset=CameraMake.objects.all()
        )

    def set_timely(self, type, value):
        self.fields['time'] = forms.DateField(
            widget=MonthPickerInput(
                format=type,
                options={
                    "format": type,
                    "showClose": False,
                    "showClear": False,
                    "showTodayButton": False,
                },
                attrs={
                    'value': value
                },
            ),
            required=False
        )

    def set_transport_type(self, transport_type):
        self.fields['transport_type'] = forms.ModelChoiceField(
            required=False,
            widget=forms.Select(
                attrs={'class': 'form-control'}),
            queryset=TransType.objects.all(),
            empty_label='All Types',
            initial=transport_type
        )

    def set_filter_type(self, filter_type):
        self.fields['filter_type'] = forms.ChoiceField(widget=forms.RadioSelect, choices=((0, 'Uploads'), (1, 'Distance'), (2, 'View Points')), initial=filter_type)

    def set_time_type(self, time_type):
        self.fields['time_type'] = forms.CharField(
            label='',
            widget=forms.TextInput(attrs={'class': 'form-control d-none', 'value': time_type}),
            required=False
        )

    def set_camera_makes(self, camera_makes):
        self.fields['camera_make'] = forms.ModelMultipleChoiceField(
            required=False,
            widget=forms.SelectMultiple(
                attrs={'class': 'form-control'}
            ),
            queryset=CameraMake.objects.all(),
            initial=camera_makes
        )

challenge/views.py
## Python packages
from datetime import datetime
import json

## Django Packages
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.shortcuts import redirect
from django.utils import timezone
from django.http import (
    Http404, HttpResponse, JsonResponse, HttpResponsePermanentRedirect, HttpResponseRedirect,
)
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.contrib.gis.geos import Point, Polygon, MultiPolygon, LinearRing, LineString
from sequence.models import Sequence
from django.db.models.expressions import F, Window
from django.db.models.functions.window import RowNumber
from django.db.models import Avg, Count, Min, Sum
## Custom Libs ##
from lib.functions import *

## Project packages
from accounts.models import CustomUser

## App packages

# That includes from .models import *
from .forms import *

############################################################################

# def handler404(request, *args, **argv):
#     response = render(request, '404.html', {})
#     response.status_code = 404
#     return response

# def handler500(request, *args, **argv):
#     response = render(request, '500.html', {})
#     response.status_code = 500
#     return response

############################################################################

MAIN_PAGE_DESCRIPTION = "Find or offer help on image collection projects to create fresh street level map data in locations where it's needed for Google Street View, Mapillary, and more..."
JOB_PAGE_DESCRIPTION = ""


############################################################################

def index(request):
    return redirect('challenge.challenge_list')

@my_login_required
def challenge_create(request):
    if request.method == "POST":
        form = ChallengeForm(request.POST)

        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.user = request.user
            geometry = json.loads(challenge.geometry)

            multipoly = MultiPolygon()
            for geo in geometry:
                coordinates = geo['geometry']['coordinates'][0]
                lineString = LineString()
                firstPoint = None
                for i in range(len(coordinates)):
                    coor = coordinates[i]
                    if i == 0:
                        firstPoint = Point(coor[0], coor[1])
                        continue
                    point = Point(coor[0], coor[1])
                    if i == 1:
                        lineString = LineString(firstPoint.coords, point.coords)
                    else:
                        lineString.append(point.coords)
                polygon = Polygon(lineString.coords)
                multipoly.append(polygon)
            challenge.multipolygon = multipoly

            for geo in geometry:
                geo['properties']['challenge_id'] = str(challenge.unique_id)
            challenge.geometry = json.dumps(geometry)

            challenge.save()
            camera_make = form.cleaned_data['camera_make']
            if not camera_make is None and len(camera_make) > 0:
                for cm in camera_make:
                    challenge.camera_make.add(cm)

            transport_type = form.cleaned_data['transport_type']
            if not transport_type is None:
                challenge.transport_type.add(transport_type)

            messages.success(request, 'A challenge was created successfully.')

            return redirect('challenge.my_challenge_list')
    else:
        form = ChallengeForm()
    content = {
        'form': form,
        'pageName': 'Create Challenge',
        'pageTitle': 'Create Challenge'
    }
    return render(request, 'challenge/create.html', content)

@my_login_required
def challenge_edit(request, unique_id):
    challenge = get_object_or_404(Challenge, unique_id=unique_id)
    if request.method == "POST":
        form = ChallengeForm(request.POST, instance=challenge)
        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.user = request.user
            challenge.updated_at = datetime.now()
            challenge.save()

            camera_make = form.cleaned_data['camera_make']
            print(camera_make)
            if not camera_make is None and len(camera_make) > 0:
                challenge.transport_type.clear()
                for cm in camera_make:
                    challenge.camera_make.add(cm)

            geometry = json.loads(challenge.geometry)

            multipoly = MultiPolygon()
            for geo in geometry:
                coordinates = geo['geometry']['coordinates'][0]
                lineString = LineString()
                firstPoint = None
                for i in range(len(coordinates)):
                    coor = coordinates[i]
                    if i == 0:
                        firstPoint = Point(coor[0], coor[1])
                        continue
                    point = Point(coor[0], coor[1])
                    if i == 1:
                        lineString = LineString(firstPoint.coords, point.coords)
                    else:
                        lineString.append(point.coords)
                polygon = Polygon(lineString.coords)
                multipoly.append(polygon)
            challenge.multipolygon = multipoly

            for geo in geometry:
                geo['properties']['challenge_id'] = str(challenge.unique_id)
            challenge.geometry = json.dumps(geometry)
            challenge.save()
            transport_type = form.cleaned_data['transport_type']
            print(transport_type.count())
            if not transport_type is None:
                challenge.transport_type.clear()
                for transport_t in transport_type:
                    challenge.transport_type.add(transport_t)
            messages.success(request, 'Challenge "%s" is updated successfully.' % challenge.name)
            return redirect('challenge.index')
    else:
        form = ChallengeForm(instance=challenge)
    content = {
        'form': form,
        'pageName': 'Edit Challenge',
        'challenge': challenge,
        'pageTitle': challenge.name + ' - Edit Challenge'
    }
    return render(request, 'challenge/edit.html', content)

@my_login_required
def my_challenge_delete(request, unique_id):
    challenge = get_object_or_404(Challenge, unique_id=unique_id)
    if challenge.user == request.user:
        if challenge.camera_make.all().count() > 0:
            for cm in challenge.camera_make.all():
                cm.delete()
        challenge.delete()
        messages.success(request, 'Challenge "%s" is deleted successfully.' % challenge.name)
    else:
        messages.error(request, "This user hasn't permission")

    return redirect('challenge.index')

def challenge_list(request):
    challenges = None
    page = 1
    if request.method == "GET":
        form = ChallengeSearchForm(request.GET)
        page = request.GET.get('page')
        if page is None:
            page = 1
        if form.is_valid():
            challenges = Challenge.objects.all().filter(is_published=True)

            name = form.cleaned_data['name']
            transport_type = form.cleaned_data['transport_type']
            expected_count_min = form.cleaned_data['expected_count_min']
            expected_count_max = form.cleaned_data['expected_count_max']
            start_time = form.cleaned_data['start_time']
            end_time = form.cleaned_data['end_time']
            camera_makes = form.cleaned_data['camera_make']

            if not name is None:
                challenges = challenges.filter(name__contains=name)
            if not transport_type is None and transport_type != 0 and transport_type != '':
                children_trans_type = TransType.objects.filter(parent_id=transport_type)
                if children_trans_type.count() > 0:
                    types = []
                    types.append(transport_type)
                    for t in children_trans_type:
                        types.append(t)
                    challenges = challenges.filter(transport_type__in=types)
                else:
                    challenges = challenges.filter(transport_type=transport_type)

            if not expected_count_min is None:
                challenges = challenges.filter(expected_count__gte=expected_count_min)
            if not expected_count_max is None:
                challenges = challenges.filter(expected_count__lte=expected_count_max)
            if not start_time is None:
                challenges = challenges.filter(end_time__gte=start_time)
            if not end_time is None:
                challenges = challenges.filter(start_time__lte=end_time)
            if not camera_makes is None and len(camera_makes) > 0:
                cs = Challenge.objects.filter(camera_make__in=camera_makes)
                challenges = challenges.filter(pk__in=cs)

    if challenges == None:
        challenges = Challenge.objects.all().filter(is_published=True)
        form = ChallengeSearchForm()

    paginator = Paginator(challenges.order_by('-created_at'), 5)

    try:
        pChallenges = paginator.page(page)
    except PageNotAnInteger:
        pChallenges = paginator.page(1)
    except EmptyPage:
        pChallenges = paginator.page(paginator.num_pages)

    first_num = 1
    last_num = paginator.num_pages
    if paginator.num_pages > 7:

templates/challenge/create.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_challenge %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/challenge_style.css' %}">{% endblock %}
{% block content %}
<div class="main-body">
    <div class="left-side d-flex flex-column justify-content-between">
        <div>
            <div class="p-4">
                <h4 class="text-center text-primary mt-3">Create Challenge</h4>

                <p>Draw the areas you are available for work:</p>

                <div class="mapbox-actions d-flex justify-content-between mb-3">
                    <div class="col-6 pl-0 pr-1">
                        <button class="btn btn-primary w-100" id="draw_polygon">Draw Polygon</button>
                    </div>

                    <div class="col-6 pr-0 pl-1">
                        <button class="btn btn-danger w-100" id="delete_polygon">Delete Polygon</button>
                    </div>
                </div>

                <form method="POST" class="post-form" id="challenge_create_form">
                    {% csrf_token %}
                    {% load bootstrap4 %}
                    {% bootstrap_css %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <div class="form-group text-right">
                        <button type="button" class="save btn btn-primary save-btn">Save</button>
                    </div>
                </form>
            </div>
        </div>
        {% include 'components/copyrite.html' %}
    </div>
    <div class="right-board bg-light">
        <div id="map"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
  <script>
    // TO MAKE THE MAP APPEAR YOU MUST
	// ADD YOUR ACCESS TOKEN FROM
	// https://account.mapbox.com
	mapboxgl.accessToken = mapboxToken;
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11', //hosted style id
        center: [-74.5, 40], // starting position
        zoom: 3 // starting zoom
    });

    var coordinatesGeocoder = function(query) {
    // match anything which looks like a decimal degrees coordinate pair
    var matches = query.match(
            /^[ ]*(?:Lat: )?(-?\d+\.?\d*)[, ]+(?:Lng: )?(-?\d+\.?\d*)[ ]*$/i
        );
        if (!matches) {
            return null;
        }

    function coordinateFeature(lng, lat) {
        return {
            center: [lng, lat],
            geometry: {
                type: 'Point',
                coordinates: [lng, lat]
            },
            place_name: 'Lat: ' + lat + ' Lng: ' + lng,
            place_type: ['coordinate'],
            properties: {},
            type: 'Feature'
        };
    }

    var coord1 = Number(matches[1]);
    var coord2 = Number(matches[2]);
    var geocodes = [];

    if (coord1 < -90 || coord1 > 90) {
        // must be lng, lat
        geocodes.push(coordinateFeature(coord1, coord2));
    }

    if (coord2 < -90 || coord2 > 90) {
        // must be lat, lng
        geocodes.push(coordinateFeature(coord2, coord1));
    }

    if (geocodes.length === 0) {
        // else could be either lng, lat or lat, lng
        geocodes.push(coordinateFeature(coord1, coord2));
        geocodes.push(coordinateFeature(coord2, coord1));
    }

    return geocodes;
    };

    map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            localGeocoder: coordinatesGeocoder,
            zoom: 1,
            placeholder: '',
            mapboxgl: mapboxgl
        }), 'top-left'
    );

    var draw = new MapboxDraw({
        displayControlsDefault: false,
        controls: {
            polygon: true,
            trash: true
        }
    });
    map.addControl(draw);

    map.on('draw.create', updateArea);
    map.on('draw.delete', updateArea);
    map.on('draw.update', updateArea);

    function updateArea(e) {
        var data = draw.getAll();
        var zoom = map.getZoom();
        console.log(zoom);
        console.log(data);
        var geometryData = [];
        data.features.forEach(function (item, index) {
            geometryData.push(item);
        });
        var geometryDataStr = JSON.stringify(geometryData);
        console.log(geometryData)
        $('#id_geometry').val(geometryDataStr);
        $('#id_zoom').val(zoom);
    }

    $('.save-btn').click(function() {
        if ($('#id_geometry').val() == '' || $('#id_geometry').val() == '[]')
        {
            Swal.fire({
                title: 'Required One or More Area.',
                icon: 'error',
                showCloseButton: true,
            })
            return false;
        }
        $('#challenge_create_form').submit()
        return true;
    })

    $('#draw_polygon').click(function() {
        $('.mapbox-gl-draw_polygon').trigger('click');
    })

    $('#delete_polygon').click(function() {
        $('.mapbox-gl-draw_trash').trigger('click');
    })
  </script>
{% endblock %}

templates/challenge/detail.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_challenge %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/challenge_style.css' %}">{% endblock %}
{% block content %}

<div class="main-body">
    <div class="left-side d-flex flex-column justify-content-between">
        <div>
            <div class="challenge-detail p-5">
                <h4 class="text-center text-primary">Challenge Detail</h4>
                <div>
                    <h6 class="">
                        Name:
                    </h6>
                    <p class="">
                        {{ challenge.name }}
                    </p>
                </div>

                <div>
                    <h6 class="">
                        Business Name:
                    </h6>
                    <p class="">
                        {{ challenge.business_name }}
                    </p>
                </div>

                <div>
                    <h6 class="">
                        Business Website:
                    </h6>
                    <p class="">
                        <a href="{{ challenge.business_website }}" target="_blank">{{ challenge.business_website }}</a>
                    </p>
                </div>

                <div>
                    <h6 class="">
                        Business Email:
                    </h6>
                    <p class="">
                        {{ challenge.business_email }}
                    </p>
                </div>

                <div>
                    <h6 class="">
                        Description:
                    </h6>
                    <p class="">
                        {{ challenge.description }}
                    </p>
                </div>

                <p class="d-none" id="id_geometry">{{ challenge.geometry }}</p>

                <div>
                    <h6 class="">
                        Date Time:
                    </h6>
                    <p class="">
                        {{ challenge.updated_at }}
                    </p>
                </div>

            </div>
        </div>
        {% include 'components/copyrite.html' %}
    </div>
    <div class="right-board bg-light">
        <div id="map"></div>
    </div>
</div>

{% endblock %}

{% block scripts %}
  <script>
    // TO MAKE THE MAP APPEAR YOU MUST
	// ADD YOUR ACCESS TOKEN FROM
	// https://account.mapbox.com
	mapboxgl.accessToken = mapboxToken;
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11', //hosted style id
        center: [-74.5, 40], // starting position
        zoom: {{ challenge.zoom }} // starting zoom
    });

    var geometryData = $('#id_geometry').text();
    console.log(geometryData);
    var geometryDataJson = JSON.parse(geometryData);
    console.log(geometryDataJson);



    map.on('load', function() {
        map.addSource('states', {
            'type': 'geojson',
            'data': {
                'type': 'FeatureCollection',
                'features': geometryDataJson
            }
        });
        map.addLayer({
            'id': 'states-layer',
            'type': 'fill',
            'source': 'states',
            'layout': {},
            'paint': {
                'fill-color': 'rgba(200, 100, 240, 0.4)',
                'fill-outline-color': 'rgba(200, 100, 240, 1)'
            }
        });
        // When a click event occurs on a feature in the states layer, open a popup at the
        // location of the click, with description HTML from its properties.
        map.on('click', 'states-layer', function (e) {
            console.log(e);
            new mapboxgl.Popup()
                .setLngLat(e.lngLat)
                .setHTML(e.features[0].properties.challenge_id)
                .addTo(map);
        });

        // Change the cursor to a pointer when the mouse is over the states layer.
        map.on('mouseenter', 'states-layer', function () {
            map.getCanvas().style.cursor = 'pointer';
        });

        // Change it back to a pointer when it leaves.
        map.on('mouseleave', 'states-layer', function () {
            map.getCanvas().style.cursor = '';
        });
    });
  </script>
{% endblock %}

templates/challenge/modal_detail.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="challengeDetailModalTitle">{{ challenge.name }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="challenge-description">
                <p>
                    {{ challenge.description }}
                </p>
            </div>

            <div class="challenge-camera-make">
                <p>
                    {{ challenge.getCameraMake }}
                </p>
            </div>

            <div class="challenge-transport-type">
                <p>
                    {{ challenge.getTrasTypes }}
                </p>
            </div>

            <div class="challenge-options">
                <p>
                    {{ challenge.start_time.date }} ~ {{ challenge.end_time.date }}
                </p>
            </div>

            <div class="challenge-created-at text-secondary">
                <h6>
                    {{ challenge.created_at }}
                </h6>
            </div>
        </div>
        {% if is_mine %}
            <div class="modal-footer d-flex flex-row justify-content-end">
                <a type="button" href="javascript:goWithSearchParam('{% url 'challenge.challenge_leaderboard' unique_id=challenge.unique_id %}')" id="show_leaderboad" class="btn btn-success text-light" >Go to Leaderboard</a>
                <a type="button" href="{% url 'challenge.my_challenge_edit' unique_id=challenge.unique_id %}" id="edit_button" class="btn btn-primary text-light" >Edit</a>
                <button type="button" id="delete_button" class="btn btn-danger text-light" >Delete</button>
                <form method="POST" action="{% url 'challenge.my_challenge_delete' unique_id=challenge.unique_id %}" id="delete_form">
                    {% csrf_token %}
                </form>
            </div>
        {% else %}
            <div class="modal-footer d-flex flex-row justify-content-end">
                <a type="button" href="javascript:goWithSearchParam('{% url 'challenge.challenge_leaderboard' unique_id=challenge.unique_id %}')" id="show_leaderboad" class="btn btn-success text-light" >Go to Leaderboard</a>
            </div>
        {% endif %}  
    </div>
</div>

<script>
    $('#delete_button').click(function() {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $('#delete_form').submit()
            }
        })
    })
</script>