api/urls.py
from django.urls import path, re_path
from . import views
from rest_framework_simplejwt import views as jwt_views
urlpatterns = [
    # re_path(r'^(?P<version>(v1))/mapillary/token/verify', views.MapillaryTokenVerify.as_view(), name='api.mapillary.token_verify'),
    re_path(r'^(?P<version>(v1))/sequence/create', views.SequenceCreate.as_view(), name="api.sequence.create"),
    re_path(r'^(?P<version>(v1))/sequence/import/(?P<unique_id>[\w-]+)/$', views.SequenceImport.as_view(), name="api.sequence.import"),
    # re_path(r'^(?P<version>(v1|v2))/sequence/import', views.SequenceImport.as_view(), name="api.sequence.import"),
]

guidebook/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.home, name='guidebook.home'),
    path('create', views.guidebook_create, name='guidebook.create'),
    path('<str:unique_id>/edit/', views.guidebook_create, name='guidebook.guidebook_edit'),
    path('list/', views.guidebook_list, name='guidebook.guidebook_list'),
    path('my-guidebook-list/', views.my_guidebook_list, name='guidebook.my_guidebook_list'),
    path('<str:unique_id>/detail/', views.guidebook_detail, name='guidebook.guidebook_detail'),
    path('<str:unique_id>/check_like/', views.check_like, name='guidebook.check_like'),
    path('<str:unique_id>/check_publish/', views.check_publish, name='guidebook.check_publish'),
    path('<str:unique_id>/delete/', views.guidebook_delete, name='guidebook.guidebook_delete'),

    path('<str:unique_id>/scene/', views.add_scene, name='guidebook.add_scene'),
    path('<str:unique_id>/ajax/save_scene/', views.ajax_add_scene, name='guidebook.ajax_add_scene'),
    path('<str:unique_id>/ajax/get_detail/', views.ajax_get_detail, name='guidebook.ajax_get_detail'),
    path('<str:unique_id>/ajax/upload_file/', views.ajax_upload_file, name='guidebook.ajax_upload_file'),
    path('<str:unique_id>/ajax/guidebook_update/', views.ajax_guidebook_update, name='guidebook.ajax_guidebook_update'),
    path('<str:unique_id>/ajax/order_scene/', views.ajax_order_scene, name='guidebook.ajax_order_scene'),
    path('<str:unique_id>/scene/ajax/save_poi/<int:pk>/', views.ajax_save_poi, name='guidebook.ajax_save_poi'),
    path('<str:unique_id>/scene/ajax/delete_poi/<int:pk>/', views.ajax_delete_poi, name='guidebook.ajax_delete_poi'),
    path('<str:unique_id>/scene/ajax/delete_scene/<int:pk>/', views.ajax_delete_scene, name='guidebook.ajax_delete_scene'),
    path('<str:unique_id>/ajax/edit/get_scene/', views.ajax_get_edit_scene, name='guidebook.ajax_get_edit_scene'),
    path('<str:unique_id>/ajax/edit/set_starting_view/', views.ajax_set_start_view, name='guidebook.ajax_set_start_view'),
    path('<str:unique_id>/ajax/get_scene/', views.ajax_get_scene, name='guidebook.ajax_get_scene'),
    path('<str:unique_id>/ajax/get_scene_list/', views.ajax_get_scene_list, name='guidebook.ajax_get_scene_list'),
]

guidebook/models.py
## Django Packages
from django.contrib.gis.db import models
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from datetime import datetime
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
from django.core.validators import RegexValidator
from storages.backends.s3boto3 import S3Boto3Storage
from django.conf import settings
from sequence.models import Tag
## Python Packages
import uuid

UserModel = get_user_model()

def image_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'guidebook/{0}/cover_image/{1}'.format(instance.unique_id, filename)

# class Tag(models.Model):
#     alphanumeric = RegexValidator(r'^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed for Username.')
#     name = models.CharField(max_length=50, unique=True, null=True, validators=[alphanumeric])
#     description = models.TextField(default=None, blank=True, null=True)
#     is_actived = models.BooleanField(default=True)
#
#     def __str__(self):
#         return self.name

def getAllTags():
    items = Tag.objects.filter(is_actived=True)
    itemsTuple = ()
    for item in items:
        itemsTuple = itemsTuple + ((item.pk, item.name),)
    print(itemsTuple)
    return itemsTuple

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'



class Guidebook(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    cover_image = models.ImageField(upload_to=image_directory_path, null=True)
    tag = models.ManyToManyField(Tag)
    is_published = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    def get_absolute_url(self):
        return reverse('guidebook.guidebook_detail', kwargs={'unique_id': str(self.unique_id)})

    def getScenes(self):
        scenes = Scene.objects.filter(guidebook=self).order_by('sort')
        return scenes

    def getScenePositions(self):
        scenes = Scene.objects.filter(guidebook=self)
        positions = []
        if scenes and scenes.count() > 0:
            for scene in scenes:
                position = [scene.lat, scene.lng]
                positions.append(position)
        return positions

    def getFirstScene(self):
        scenes = Scene.objects.filter(guidebook=self).order_by('sort')
        if scenes and scenes.count() > 0:
            firstScene = scenes[0]
            return firstScene
        else:
            return ''

    def getSceneCount(self):
        scenes = Scene.objects.filter(guidebook=self)
        return scenes.count()

    def getLikeCount(self):
        liked_guidebook = GuidebookLike.objects.filter(guidebook=self)
        if not liked_guidebook:
            return 0
        else:
            return liked_guidebook.count()

    def getShortDescription(self):
        description = self.description
        if len(description) > 100:
            return description[0:100] + '...'
        else:
            return description

    def getTagStr(self):
        tags = []
        if self.tag is None:
            return ''
        for tag in self.tag.all():
            if tag and tag.is_actived:
                tags.append(tag.name)

        if len(tags) > 0:
            return ', '.join(tags)
        else:
            return ''

    def getTags(self):
        tags = []
        if self.tag is None:
            return []
        for tag in self.tag.all():
            if tag and tag.is_actived:
                tags.append(tag.name)
        return tags

    def getCoverImage(self):
        scenes = Scene.objects.filter(guidebook=self)
        if scenes.count() > 0:
            return scenes[0].image_key
        else:
            return None

class GuidebookLike(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    guidebook = models.ForeignKey(Guidebook, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

class POICategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'POI Categories'

class Scene(models.Model):
    guidebook = models.ForeignKey(Guidebook, on_delete=models.CASCADE)
    image_key = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True)
    lat = models.FloatField(default=0)
    lng = models.FloatField(default=0)
    start_x = models.FloatField(default=0.5)
    start_y = models.FloatField(default=0.5)
    sort = models.IntegerField(default=1, null=True)
    image_url = models.CharField(max_length=100, null=True)

    def getPOICount(self):
        pois = PointOfInterest.objects.filter(scene=self)
        return pois.count()

    def getPOICategories(self):
        pois = PointOfInterest.objects.filter(scene=self)
        categories = []
        if pois.count() > 0:
            for poi in pois:
                if not poi.category.name in categories:
                    categories.append(poi.category.name)
        if len(categories) > 0:
            return ', '.join(categories)
        else:
            return ''

class PointOfInterest(models.Model):
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default='')
    description = models.TextField(default='')
    position_x = models.FloatField(default=0)
    position_y = models.FloatField(default=0)
    category = models.ForeignKey(POICategory, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.title









guidebook/forms.py
## Django Packages
from django import forms
from django_select2 import forms as s2forms

## App packages
from .models import *
from tags_input import fields
from lib.classes import CustomTagsInputField
############################################################################
############################################################################

class GuidebookForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'data-validation': 'required'}),
        required=False
    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'data-validation': 'required'}),
        required=False
    )
    category = forms.ModelChoiceField(
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control', 'data-validation': 'required'}),
        queryset=Category.objects.all(),
        to_field_name='pk',
        empty_label=None
    )

    tag = CustomTagsInputField(
        Tag.objects.filter(is_actived=True),
        create_missing=True,
        required=False,
    )

    # cover_image = forms.FileField(
    #     widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'data-validation': 'required'}),
    #     required=False
    # )
    # is_published = forms.ChoiceField(
    #     widget=forms.RadioSelect(attrs={'class': 'd-none', 'disabled': 'disabled'}),
    #     choices=(('True', 'Published'), ('False', 'Unpublished')),
    #     required=False,
    #     label=''
    # )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['tag'] = CustomTagsInputField(
            Tag.objects.filter(is_actived=True),
            create_missing=True,
            required=False,
        )

    class Meta:
        model = Guidebook
        fields = (
            'name',
            'description',
            # 'cover_image',
            'category',
            'tag',
            # 'is_published',
        )

class GuidebookImageForm(forms.ModelForm):
    cover_image = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
        required=False
    )

    class Meta:
        model = Guidebook
        fields = (
            'cover_image',
        )

class SceneForm(forms.Form):
    image_key = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
    )
    title = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Scene Title'}),
    )
    description = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Scene Description', 'rows': 2, 'style': 'resize: none;'}),
        required=False
    )

    lat = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
    )
    lng = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
    )

    start_x = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
        required=False
    )

    start_y = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control d-none'}),
        required=False
    )

    class Meta:
        fields = (
            'image_key',
            'title',
            'description',
            'lat',
            'lng',
            'start_x',
            'start_y'
        )

class PointOfInterestForm(forms.ModelForm):
    title = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Point of Interest Title'}),
    )
    description = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Point of Interest Description', 'rows': 3}),
        required=False
    )
    category = forms.ModelChoiceField(
        required=False,
        label='',
        widget=forms.Select(
            attrs={'class': 'form-control'}),
        queryset=POICategory.objects.all(),
        to_field_name='pk',
        empty_label=None
    )

    class Meta:
        model = PointOfInterest
        fields = (
            'title',
            'description'
        )

class GuidebookSearchForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'] = forms.CharField(
            label='Guidebook Name',
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            required=False
        )

        self.fields['image_key'] = forms.CharField(
            label='Image Key',
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            required=False
        )

        self.fields['category'] = forms.ModelChoiceField(
            required=False,
            widget=forms.Select(
                attrs={'class': 'form-control'}),
            queryset=Category.objects.all(),
            empty_label="All Categories"
        )
        self.fields['tag'] = CustomTagsInputField(
            Tag.objects.filter(is_actived=True),
            create_missing=False,
            required=False,
        )

        self.fields['username'] = forms.CharField(
            label='Username',
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            required=False
        )

        self.fields['like'] = forms.ChoiceField(
            label='Like',
            widget=forms.RadioSelect(),
            required=False,
            choices=(('all', 'All'), ('true', 'Liked'), ('false', 'Unliked')),
        )

    def _my(self, username):
        self.fields['username'] = forms.CharField(
            label='Username',
            widget=forms.TextInput(attrs={'class': 'form-control d-none', 'value': username}),
            required=False
        )


templates/guidebook/create_main.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block app_guidebook %}active{% endblock %}
{% block app_style %}<link rel="stylesheet" href="{% static 'css/guidebook_style.css' %}">{% endblock %}
{% block content %}
<div class="main-body">
    <div class="page-header d-none">
        <div class="pt-3 mb-3">
            <h4>
                {{ pageName }}
            </h4>
        </div>

        <p>
            {{ pageDescription }}
        </p>
    </div>
    <div class="w-100 mt-5 d-flex justify-content-center">
        <form method="POST" class="post-form" id="guidebook_create_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class="form-group d-flex justify-content-between">
                <button type="button" class="btn btn-info" onclick="window.history.back()">Back</button>
                <button type="submit" class="save btn btn-primary save-btn">Continue</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/guidebook/modal_detail.html
{% load static %}
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="guidebookDetailModalTitle">{{ guidebook.name }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div>
                <div class="guidebook-description">
                    <p>
                        {{ guidebook.description }}
                    </p>
                </div>
            </div>
        </div>
        <div class="modal-footer d-flex flex-row justify-content-end">
            <a type="button" href="{% url 'guidebook.guidebook_detail' unique_id=guidebook.unique_id %}" id="show_guidebook" class="btn btn-success text-light" >Go to Detail Page</a>
        </div>
    </div>
</div>

templates/guidebook/poi_box.html
<div class="card poi" id="poi_{{ poi.pk }}">
    <div class="card-header " id="poi_header_{{ poi.pk }}">
        <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapse-button" data-poi-id="{{ poi.pk }}" type="button" data-toggle="collapse" data-target="#poi_body_{{ poi.pk }}" aria-expanded="true" aria-controls="collapseOne">
                {{ poi.title }}
            </button>
        </h2>
    </div>
    <div id="poi_body_{{ poi.pk }}" class="collapse" aria-labelledby="poi_header_{{ poi.pk }}" data-parent="#poi_list">
        <div class="card-body">
            <div class="poi-description">
                <span>{{ poi.description }}</span>
            </div>
            <div class="poi-cetegory mt-2" style="color: blueviolet;">
                <p class="mb-1">
                    {{ poi.category }}
                </p>
            </div>
            <div class="d-none">
                <div class=""><span>X: </span><span class="position-x">{{ poi.position_x }}</span></div>
                <div class=""><span>Y: </span><span class="position-y">{{ poi.position_y }}</span></div>
            </div>
        </div>
    </div>
</div>

templates/guidebook/poi_edit_box.html
<div class="card poi" id="poi_{{ poi.pk }}">
    <div class="card-header " id="poi_header_{{ poi.pk }}">
        <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left collapse-button" data-poi-id="{{ poi.pk }}" type="button" data-toggle="collapse" data-target="#poi_body_{{ poi.pk }}" aria-expanded="true" aria-controls="collapseOne">
{#                {{ poi.pk }}#}
                {{ poi.title }}
            </button>
        </h2>
    </div>

    <div id="poi_body_{{ poi.pk }}" class="collapse" aria-labelledby="poi_header_{{ poi.pk }}" data-parent="#poi_list">
        <div class="card-body">
            <form method="post">
                {{ poi_form.as_p }}

                <div class="d-flex align-items-center justify-content-between">
                    <div class="text-left">
                        <div class="d-none"><span>X: </span><span class="position-x">{{ poi.position_x }}</span></div>
                        <div class="d-none"><span>Y: </span><span class="position-y">{{ poi.position_y }}</span></div>
                    </div>

                    <div class="text-right">
                        <button type="button" class="save btn btn-danger delete-btn delete-poi-button" data-poi-id="{{ poi.pk }}" >Delete</button>
                        <button type="button" class="save btn btn-primary save-btn save-poi-button" data-poi-id="{{ poi.pk }}" >Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/guidebook/scene_edit_box.html
<div class="list_item">
    <div class="scene-box p-1 mt-2 mb-2" id="scene_{{ scene.pk }}" data-scene-id="{{ scene.pk }}" data-image_key="{{ scene.image_key }}" style="cursor: pointer">
        <form method="POST" class="post-form has-validation-callback" id="add_scene_form_{{ scene.pk }}">
            {% csrf_token %}
            <input type="number" name="scene_id" class="d-none" value="{{ scene.pk }}" id="id_scene_id">
            <input type="text" name="image_key" class="form-control d-none" value="{{ scene.image_key }}" required="" id="id_image_key">
            <input type="text" name="title" class="form-control mb-1" disabled="disabled" value="{{ scene.title }}" placeholder="Scene Title" required="" id="id_title">
            <textarea name="description" cols="40" rows="3" disabled class="form-control mb-1" placeholder="Scene Description" style="resize: none;" id="id_description">{{ scene.description }}</textarea>
            <input type="text" name="lat" class="form-control d-none" value="{{ scene.lat }}" required="" id="id_lat">
            <input type="text" name="lng" class="form-control d-none" value="{{ scene.lng }}" required="" id="id_lng">
            <input type="text" name="start_x" class="form-control d-none" value="{{ scene.start_x }}" required="" id="id_start_x">
            <input type="text" name="start_y" class="form-control d-none" value="{{ scene.start_y }}" required="" id="id_start_y">
            <div class="text-right">
                <button type="button" class="btn btn-sm btn-info point_list" onclick="showPOIList('{{ scene.pk }}')" data-scene-id="{{ scene.pk }}">Edit POI's ({{ scene.getPOICount }})</button>
                <button type="button" id="change_scene_button" class="save btn btn-sm btn-warning change-btn" onclick="enable_scene_form({{ scene.pk }})">Edit Scene</button>
                <button type="button" id="save_scene_button" class="save btn btn-sm btn-primary save-btn d-none" onclick="saveScene('{% url "guidebook.ajax_add_scene" unique_id=guidebook.unique_id %}', {{ scene.pk }})">Save</button>
                <button type="button" class="btn btn-sm btn-danger delete_scene_button" data-scene-id="{{ scene.pk }}">Delete</button>
            </div>
        </form>
    </div>
</div>